version: "3.9"

volumes:
  db_webservice_data:
    driver: local
  db_administrative_panel_data:
    driver: local

services:
  app:
    build: ./app
    container_name: app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - API_URL=http://172.26.0.1:3004/
    ports:
      - "8080:80"
    depends_on:
      - api_app
      - api_webservice

  api_app:
    build: ./api
    container_name: api_app
    entrypoint: sh -c "npm install && npm run seed && npm run start:dev"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - DB_HOST=172.26.0.1
      - DB_HOST_T=172.26.0.1
      - DB_HOST_H=172.26.0.1
      - WEB_SERVICE_URL=http://172.26.0.1:3001
    ports:
      - "3004:3004"
    depends_on:
      - db_administrative_panel

  api_webservice:
    build: ./webservice_api
    container_name: webservice
    entrypoint: sh -c "npm install && npm run seed && npm run start:dev"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - DB_HOST=172.26.0.1
      - DB_HOST_T=172.26.0.1
      - DB_HOST_H=172.26.0.1
    ports:
      - "3001:3001"
    depends_on:
      - db_daily_consumption

  db_administrative_panel:
    image: postgres:latest
    container_name: administrative_panel_db
    expose:
      - 5433
    volumes:
      - db_administrative_panel_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      POSTGRES_DB: administrative_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  db_daily_consumption:
    image: postgres:latest
    container_name: daily_consumption_db
    expose:
      - 5432
    volumes:
      - db_webservice_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      POSTGRES_DB: daily_consumption_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
