version: "3.9"

volumes:
  db_webservice_data:
    driver: local
  db_administrative_panel_data:
    driver: local

services:
  app:
    build: ./app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - API_APP_PORT=3004
    ports:
      - "3000:3000"
    depends_on:
      - api_app
      - api_webservice

  api_app:
    build: ./api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - API_WEBSERVICE_PORT=3001
      - DB_ADMINISTRATIVE_PANEL_PORT=5433
    ports:
      - "3004:3004"
    depends_on:
      - db_administrative_panel

  api_webservice:
    build: ./webservice_api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - DB_DAILY_CONSUMPTION_PORT=5432
    ports:
      - "3001:3001"
    depends_on:
      - db_daily_consumption

  db_administrative_panel:
    image: postgres:latest
    container_name: administrative_panel_db
    expose:
      - 5433
    volumes:
      - db_administrative_panel_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      POSTGRES_DB: administrative_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  db_daily_consumption:
    image: postgres:latest
    container_name: daily_consumption_db
    expose:
      - 5432
    volumes:
      - db_webservice_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      POSTGRES_DB: daily_consumption_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
